server:
  port: 8081

spring:
  application:
    name: payment-8081

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://36.26.94.156:3306/cloud

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

mybatis:
  typeAliasesPackage: com.cloud.payment.entities
  mapperLocations: classpath:mapper/*.xml
