server:
  port: 8086

spring:
  application:
    name: payment-consul
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
      host: localhost
      port: 8500