server:
  port: 3344

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: config3344
    prefer-ip-address: true

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: git@github.com:fyz123/springcloud-config-git.git #GitHub上面的git仓库名字
          ####搜索目录
          search-paths: config-repo
      ####读取分支
      label: master

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'