spring:
  application:
    name: gateway-9527
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: route1
          uri: lb://PAYMENT
          #uri: http://localhost:8081
          predicates:
            - Path=/payment/*


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: gateway9527
    prefer-ip-address: true

server:
  port: 9527