server:
  port: 7002

eureka:
  instance:
    hostname: eureka7001
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

devtools:
  restart:
    enabled: true