server:
  port: 80

spring:
  application:
    name: consumer_consul
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
      host: localhost
      port: 8500